services:
  unbound-dockerized:
    image: bruijnes/unbound-dockerized
    container_name: unbound-dockerized
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./unbound.conf:/app/unbound.conf
    restart: unless-stopped