services:
  unbound-dockerized:
    build: ./build
    image: bruijnes/unbound-dockerized
    container_name: unbound-dockerized
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: unless-stopped
    environment:
      - INTERFACE_V4="0.0.0.0"
      - INTERFACE_V6="::0"
      - ALLOW_V4="0.0.0.0/0"
      - ALLOW_V6="::/0"